# Generated by Django 2.0.2 on 2018-03-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCollaborativefilteringItemRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('number_0', models.BigIntegerField(blank=True, db_column='0', null=True)),
                ('number_1', models.BigIntegerField(blank=True, db_column='1', null=True)),
                ('number_2', models.BigIntegerField(blank=True, db_column='2', null=True)),
                ('number_3', models.BigIntegerField(blank=True, db_column='3', null=True)),
                ('number_4', models.BigIntegerField(blank=True, db_column='4', null=True)),
                ('number_5', models.BigIntegerField(blank=True, db_column='5', null=True)),
                ('number_6', models.BigIntegerField(blank=True, db_column='6', null=True)),
                ('number_7', models.BigIntegerField(blank=True, db_column='7', null=True)),
                ('number_8', models.BigIntegerField(blank=True, db_column='8', null=True)),
                ('number_9', models.BigIntegerField(blank=True, db_column='9', null=True)),
                ('movieid', models.BigIntegerField(blank=True, db_column='movieId', null=True)),
            ],
            options={
                'db_table': 'Simple_CollaborativeFiltering_item_recommendation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SimpleCollaborativefilteringSimilarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('number_0', models.BigIntegerField(blank=True, db_column='0', null=True)),
                ('number_1', models.BigIntegerField(blank=True, db_column='1', null=True)),
                ('number_2', models.BigIntegerField(blank=True, db_column='2', null=True)),
                ('number_3', models.BigIntegerField(blank=True, db_column='3', null=True)),
                ('number_4', models.BigIntegerField(blank=True, db_column='4', null=True)),
                ('number_5', models.BigIntegerField(blank=True, db_column='5', null=True)),
                ('number_6', models.BigIntegerField(blank=True, db_column='6', null=True)),
                ('number_7', models.BigIntegerField(blank=True, db_column='7', null=True)),
                ('number_8', models.BigIntegerField(blank=True, db_column='8', null=True)),
                ('number_9', models.BigIntegerField(blank=True, db_column='9', null=True)),
                ('userid', models.BigIntegerField(blank=True, db_column='userId', null=True)),
            ],
            options={
                'db_table': 'Simple_CollaborativeFiltering_similar_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SimpleCollaborativefilteringUserRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('number_0', models.BigIntegerField(blank=True, db_column='0', null=True)),
                ('number_1', models.BigIntegerField(blank=True, db_column='1', null=True)),
                ('number_2', models.BigIntegerField(blank=True, db_column='2', null=True)),
                ('number_3', models.BigIntegerField(blank=True, db_column='3', null=True)),
                ('number_4', models.BigIntegerField(blank=True, db_column='4', null=True)),
                ('number_5', models.BigIntegerField(blank=True, db_column='5', null=True)),
                ('number_6', models.BigIntegerField(blank=True, db_column='6', null=True)),
                ('number_7', models.BigIntegerField(blank=True, db_column='7', null=True)),
                ('number_8', models.BigIntegerField(blank=True, db_column='8', null=True)),
                ('userid', models.BigIntegerField(blank=True, db_column='userId', null=True)),
            ],
            options={
                'db_table': 'Simple_CollaborativeFiltering_user_recommendation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SimpleContentbasedfiltering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('number_0', models.BigIntegerField(blank=True, db_column='0', null=True)),
                ('number_1', models.BigIntegerField(blank=True, db_column='1', null=True)),
                ('number_2', models.BigIntegerField(blank=True, db_column='2', null=True)),
                ('number_3', models.BigIntegerField(blank=True, db_column='3', null=True)),
                ('number_4', models.BigIntegerField(blank=True, db_column='4', null=True)),
                ('number_5', models.BigIntegerField(blank=True, db_column='5', null=True)),
                ('number_6', models.BigIntegerField(blank=True, db_column='6', null=True)),
                ('number_7', models.BigIntegerField(blank=True, db_column='7', null=True)),
                ('number_8', models.BigIntegerField(blank=True, db_column='8', null=True)),
                ('number_9', models.BigIntegerField(blank=True, db_column='9', null=True)),
                ('movieid', models.BigIntegerField(blank=True, db_column='movieId', null=True)),
            ],
            options={
                'db_table': 'Simple_ContentBasedFiltering',
                'managed': True,
            },
        ),
    ]
