# Generated by Django 2.0.2 on 2018-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_simplecollaborativefilteringitemrecommendation_simplecollaborativefilteringsimilaruser_simplecollabo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularitybasedfiltering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True)),
                ('number_0', models.BigIntegerField(blank=True, db_column='0', null=True)),
                ('number_1', models.BigIntegerField(blank=True, db_column='1', null=True)),
                ('number_2', models.BigIntegerField(blank=True, db_column='2', null=True)),
                ('number_3', models.BigIntegerField(blank=True, db_column='3', null=True)),
                ('number_4', models.BigIntegerField(blank=True, db_column='4', null=True)),
                ('number_5', models.BigIntegerField(blank=True, db_column='5', null=True)),
                ('number_6', models.BigIntegerField(blank=True, db_column='6', null=True)),
                ('number_7', models.BigIntegerField(blank=True, db_column='7', null=True)),
                ('number_8', models.BigIntegerField(blank=True, db_column='8', null=True)),
                ('number_9', models.BigIntegerField(blank=True, db_column='9', null=True)),
                ('categories', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PopularityBasedFiltering',
                'managed': True,
            },
        ),
    ]
